
version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/Weekly_FNO_Analysis_With_OI.xlsx:/app/Weekly_FNO_Analysis_With_OI.xlsx
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8000/api/top-fno-picks
